version: "3"
services:
  nginx:
    build: nginx  
    ports:
      - 80:80
      - 443:443
    volumes:
     - ./prestashop:/app/prestashop
     #- ./../prestashop.conf:/etc/apache2/sites-enabled/prestashop.conf

