version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress/wordpress
      - ./prestashop:/prestashop
      - ./conf/vhostnginx.conf:/etc/nginx/conf.d/vhost.conf
      - ./conf/wordpress.conf:/etc/nginx/conf.d/wordpress.conf
      - ./conf/example.crt:/cert/certificado.crt
      - ./conf/example.key:/cert/chave.key
  prestashop:
    build: conf
    volumes:
      - ./conf/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
      - ./prestashop:/prestashop

  db:
    image: mariadb

    environment:
      MARIADB_ROOT_PASSWORD: abc123.
      MARIADB_DATABASE: presta
      MARIADB_USER: presta
      MARIADB_PASSWORD: presta
    volumes:
      - basedatos:/var/lib/mysql
      - ./db:/db
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
volumes:
  basedatos: