<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGUmhvju\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGUmhvju/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGUmhvju.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerGUmhvju\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerGUmhvju\appAppKernelProdContainer([
    'container.build_hash' => 'GUmhvju',
    'container.build_id' => 'df1d040f',
    'container.build_time' => 1685954070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGUmhvju');
